# Generated by Django 4.1.7 on 2023-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=20)),
                ('task_details', models.TextField()),
                ('due_date', models.DateField(default='2000-01-01')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
