# Generated by Django 4.1.7 on 2023-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_tasks_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('personal', 'personal'), ('work', 'work'), ('wishlist', 'wishlist')], max_length=100),
        ),
    ]
